//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastFMBrowser.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LastFMDataEntities : DbContext
    {
        public LastFMDataEntities()
            : base("name=LastFMDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lnkUserArtist> lnkUserArtists { get; set; }
        public virtual DbSet<lnkUserTagArtist> lnkUserTagArtists { get; set; }
        public virtual DbSet<tblArtist> tblArtists { get; set; }
        public virtual DbSet<tblTag> tblTags { get; set; }
        public virtual DbSet<tblTrack> tblTracks { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<sysMenuList> sysMenuLists { get; set; }
    
        public virtual ObjectResult<GET_SIMILAR_ARTISTS_Result> GET_SIMILAR_ARTISTS(Nullable<long> artistID)
        {
            var artistIDParameter = artistID.HasValue ?
                new ObjectParameter("ArtistID", artistID) :
                new ObjectParameter("ArtistID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SIMILAR_ARTISTS_Result>("GET_SIMILAR_ARTISTS", artistIDParameter);
        }
    
        public virtual int TAG_ARTIST(Nullable<long> uSERID, Nullable<long> aRTIST, string tAGVALUE)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var aRTISTParameter = aRTIST.HasValue ?
                new ObjectParameter("ARTIST", aRTIST) :
                new ObjectParameter("ARTIST", typeof(long));
    
            var tAGVALUEParameter = tAGVALUE != null ?
                new ObjectParameter("TAGVALUE", tAGVALUE) :
                new ObjectParameter("TAGVALUE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TAG_ARTIST", uSERIDParameter, aRTISTParameter, tAGVALUEParameter);
        }
    
        public virtual int REMOVE_TAG(Nullable<long> uSERID, Nullable<long> aRTIST, string tAGVALUE)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var aRTISTParameter = aRTIST.HasValue ?
                new ObjectParameter("ARTIST", aRTIST) :
                new ObjectParameter("ARTIST", typeof(long));
    
            var tAGVALUEParameter = tAGVALUE != null ?
                new ObjectParameter("TAGVALUE", tAGVALUE) :
                new ObjectParameter("TAGVALUE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REMOVE_TAG", uSERIDParameter, aRTISTParameter, tAGVALUEParameter);
        }
    
        public virtual ObjectResult<FIND_ARTIST_LISTENERS_Result> FIND_ARTIST_LISTENERS(Nullable<long> uSERID, Nullable<long> aRTIST)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var aRTISTParameter = aRTIST.HasValue ?
                new ObjectParameter("ARTIST", aRTIST) :
                new ObjectParameter("ARTIST", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FIND_ARTIST_LISTENERS_Result>("FIND_ARTIST_LISTENERS", uSERIDParameter, aRTISTParameter);
        }
    
        public virtual ObjectResult<FIND_TOP_TAGS_Result> FIND_TOP_TAGS(Nullable<long> aRTIST)
        {
            var aRTISTParameter = aRTIST.HasValue ?
                new ObjectParameter("ARTIST", aRTIST) :
                new ObjectParameter("ARTIST", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FIND_TOP_TAGS_Result>("FIND_TOP_TAGS", aRTISTParameter);
        }
    
        public virtual ObjectResult<FIND_ARTISTS_WITH_TAG_Result> FIND_ARTISTS_WITH_TAG(string tAG)
        {
            var tAGParameter = tAG != null ?
                new ObjectParameter("TAG", tAG) :
                new ObjectParameter("TAG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FIND_ARTISTS_WITH_TAG_Result>("FIND_ARTISTS_WITH_TAG", tAGParameter);
        }
    
        public virtual ObjectResult<ARTIST_SEARCH_Result> ARTIST_SEARCH(string sEARCHTERM)
        {
            var sEARCHTERMParameter = sEARCHTERM != null ?
                new ObjectParameter("SEARCHTERM", sEARCHTERM) :
                new ObjectParameter("SEARCHTERM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ARTIST_SEARCH_Result>("ARTIST_SEARCH", sEARCHTERMParameter);
        }
    
        public virtual ObjectResult<FIND_TOP_TRACKS_Result> FIND_TOP_TRACKS(Nullable<long> aRTIST)
        {
            var aRTISTParameter = aRTIST.HasValue ?
                new ObjectParameter("ARTIST", aRTIST) :
                new ObjectParameter("ARTIST", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FIND_TOP_TRACKS_Result>("FIND_TOP_TRACKS", aRTISTParameter);
        }
    
        public virtual ObjectResult<string> FIND_USER_NAME(Nullable<long> uSERID)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FIND_USER_NAME", uSERIDParameter);
        }
    
        public virtual ObjectResult<string> FIND_USER_ARTIST_TAGS(Nullable<long> uSERID, Nullable<long> aRTIST)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(long));
    
            var aRTISTParameter = aRTIST.HasValue ?
                new ObjectParameter("ARTIST", aRTIST) :
                new ObjectParameter("ARTIST", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FIND_USER_ARTIST_TAGS", uSERIDParameter, aRTISTParameter);
        }
    }
}
