//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastFMBrowser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkUserTagArtist
    {
        public long UserID { get; set; }
        public long ArtistID { get; set; }
        public int TagID { get; set; }
    
        public virtual tblArtist tblArtist { get; set; }
        public virtual tblTag tblTag { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
