//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastFMBrowser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysMenuList
    {
        public long menuID { get; set; }
        public string menuText { get; set; }
        public string menuSubFormName { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> isDefault { get; set; }
    }
}
