//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastFMBrowser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArtist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArtist()
        {
            this.lnkUserArtists = new HashSet<lnkUserArtist>();
            this.lnkUserTagArtists = new HashSet<lnkUserTagArtist>();
            this.tblTracks = new HashSet<tblTrack>();
        }
    
        public long ArtistID { get; set; }
        public string ArtistName { get; set; }
        public string BandURL { get; set; }
        public string BandPictureURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lnkUserArtist> lnkUserArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lnkUserTagArtist> lnkUserTagArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrack> tblTracks { get; set; }
    }
}
